#spring.application.name=EMOTIONAL HOME COMPANION
#spring.data.mongodb.uri=mongodb://localhost:27018/AI_Emotion_Home

#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EmotionalHomeDB;encrypt=true;trustServerCertificate=true
#spring.datasource.username=MinhLuan
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#server.port=8080


spring.application.name=EMOTIONAL_HOME_COMPANION
spring.data.mongodb.uri=mongodb://localhost:27017/Emotion_home
logging.level.org.springframework.data.mongodb=DEBUG
# Tạm thời bỏ qua cấu hình Database để Demo AI
# spring.data.mongodb.uri=...
# spring.datasource.url=...

# Để Render tự cấp Port (Quan trọng)
server.port=${PORT:8080}

# Tắt thông báo lỗi Hibernate nếu có
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false